### PR TITLE
Update wording

### PR DESCRIPTION
**Pull request by woook**
This is not a diagnostic report.
Added suggested text from nationally agreed letter for negative results.

---
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/gel_reports/10)

### CODE REVIEW

**Comment by andyb3** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[gel_cover_report_template.html, line 115 at r1](https://beta.reviewable.io/reviews/moka-guys/gel_reports/10#-L9jmFrh9KysVzJHYY_8:-L9jmFri8ftORD1gVlcZ:b-ipe3mk) ([raw file](https://github.com/moka-guys/gel_reports/blob/0bf074d72ee0c20f3304b5bbf3570496a1f08ff5/gel_cover_report_template.html#L115)):*
> ```
> her clinical presentation.
> ```
Please make this gender neutral!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/moka-guys/gel_reports/10)*

**Comment by andyb3** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/moka-guys/gel_reports/10)*

**Comment by woook** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[gel_cover_report_template.html, line 115 at r1](https://beta.reviewable.io/reviews/moka-guys/gel_reports/10#-L9jmFrh9KysVzJHYY_8:-L9k4Bx1A780JoCmPaUU:b-896fix) ([raw file](https://github.com/moka-guys/gel_reports/blob/0bf074d72ee0c20f3304b5bbf3570496a1f08ff5/gel_cover_report_template.html#L115)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

> ```
> her clinical presentation.
> ```
Please make this gender neutral!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/moka-guys/gel_reports/10)*

**Comment by andyb3** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/moka-guys/gel_reports/10#-:-L9k53jDB83U7QOIt4A6:bnfp4nl)*

**Pull request merged**
