### PR TITLE
change output file name, and change name of technical report fixes #5…

### LINKED ISSUE #5: Remove need for participant ID in html filename - just IR-ID should be sufficient

### PR DESCRIPTION
**Pull request by aledj2**
…, #6 #3

---
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/gel_reports/8)

### CODE REVIEW

**Comment by woook** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[gel_cover_report.py, line 137 at r1](https://reviewable.io:443/reviews/moka-guys/gel_reports/8#-L6pcrv0QJE7QXra7Rm0:-L6pcrv0QJE7QXra7Rm1:b769kgy) ([raw file](https://github.com/moka-guys/gel_reports/blob/db49221e0de8ed1cc054683a2eeb82fe20c89c1f/gel_cover_report.py#L137)):*
> containingt he technical reports
containing the 100K clinical html reports

---

*[gel_cover_report.py, line 149 at r1](https://reviewable.io:443/reviews/moka-guys/gel_reports/8#-L6pdEO8tY0TTXxStYza:-L6pdEO8tY0TTXxStYzb:b-i66riu) ([raw file](https://github.com/moka-guys/gel_reports/blob/db49221e0de8ed1cc054683a2eeb82fe20c89c1f/gel_cover_report.py#L149)):*
> ```Python
> 			)
> 	# create an empty list to hold all the reports which match the search pattern
> 	list_of_html_reports = []
> ```

Will there always be a small number of reports in the folder?
(I find creating a list is an inefficient approach)

How about using scandir?
https://pypi.python.org/pypi/scandir

---

*[gel_cover_report.py, line 159 at r1](https://reviewable.io:443/reviews/moka-guys/gel_reports/8#-L6pdTB9OPGc9Pmgk3YP:-L6pdTBA2Kjwuhhfb3WK:bzabgak) ([raw file](https://github.com/moka-guys/gel_reports/blob/db49221e0de8ed1cc054683a2eeb82fe20c89c1f/gel_cover_report.py#L159)):*
> S:\Genetics\Bioinformatics\GeL\\technical_reports.
Why inconsistent \ & \\ in the file path?
Anyway, please can we use the gel_original_report_folder variable rather than hard coding this file path? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/gel_reports/8)*

**Comment by aledj2** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[gel_cover_report.py, line 137 at r1](https://reviewable.io:443/reviews/moka-guys/gel_reports/8#-L6pcrv0QJE7QXra7Rm0:-L7YsZCP2KPmvM9z5FM_:b-896fix) ([raw file](https://github.com/moka-guys/gel_reports/blob/db49221e0de8ed1cc054683a2eeb82fe20c89c1f/gel_cover_report.py#L137)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> containingt he technical reports
containing the 100K clinical html reports
</blockquote></details>

Done.

---

*[gel_cover_report.py, line 149 at r1](https://reviewable.io:443/reviews/moka-guys/gel_reports/8#-L6pdEO8tY0TTXxStYza:-L7Z7qqkaDmjhR_dX2Ds:bksk21n) ([raw file](https://github.com/moka-guys/gel_reports/blob/db49221e0de8ed1cc054683a2eeb82fe20c89c1f/gel_cover_report.py#L149)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Will there always be a small number of reports in the folder?
(I find creating a list is an inefficient approach)

How about using scandir?
https://pypi.python.org/pypi/scandir
</blockquote></details>

scandir looks like it lists or loops through the files in a folder quicker than os.listdir, but switching modules won't remove the need for a list here. I'm trying to find all interim reports  for our patient found in the folder. If there is just one, that's great, and after looping through all files we have the file name. If there is 0 or more than one we stop. 

I've tried using scandir and had issues but this new approach is a bit more efficient?

---

*[gel_cover_report.py, line 159 at r1](https://reviewable.io:443/reviews/moka-guys/gel_reports/8#-L6pdTB9OPGc9Pmgk3YP:-L7YsnMe41ZnS130WsA-:bqkxs7) ([raw file](https://github.com/moka-guys/gel_reports/blob/db49221e0de8ed1cc054683a2eeb82fe20c89c1f/gel_cover_report.py#L159)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> S:\Genetics\Bioinformatics\GeL\\technical_reports.
Why inconsistent \ & \\ in the file path?
Anyway, please can we use the gel_original_report_folder variable rather than hard coding this file path? 
</blockquote></details>

This is text for a message box. As it's a string \t gets converted into a tab so this needs to be escaped. 
The reason I'm not using a variable is because this would be displayed to a end user who may not know that \\gstt.local\shared\ is the S drive

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/gel_reports/8)*

**Comment by aledj2** [comment]
+@woook

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/gel_reports/8#-:-L8DgfHWXCigxf3TJxbi:b-bgdetj)*

**Comment by woook** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/gel_reports/8#-:-L8HuLsq5DdVEUvWIseM:bnfp4nl)*

**Pull request merged**
