### PR TITLE
Update for batch processing

### PR DESCRIPTION
**Pull request by andyb3**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/gel_reports/11)

### CODE REVIEW

**Comment by aledj2** [comment]
+@aledj2 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/gel_reports/11#-:-LCDMJ5a2SX1nOPIFovJ:bweg3f8)*

**Comment by aledj2** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[gel_cover_report.py, line 39 at r1](https://reviewable.io/reviews/moka-guys/gel_reports/11#-LCDNknn5Ix2Kfzo9dGH:-LCDNknn5Ix2Kfzo9dGI:b-5hhmya) ([raw file](https://github.com/moka-guys/gel_reports/blob/8ec6adbf47423147c7664660fa66c4cd2d19d2e0/gel_cover_report.py#L39)):*
> ```Python
> 	parser = argparse.ArgumentParser(description='Creates cover page for GeL results and attaches to report provided by GeL')
> 	# Define the arguments that will be taken. Multiple NGSTestIDs from NGSTest table in Moka can be passed as arguments.
> 	parser.add_argument('-n', metavar='NGSTestID', required=True, type=int, nargs='+', help='Moka NGSTestID from NGSTest table')
> ```

sorry, could you explain nargs='+' please

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/gel_reports/11)*

**Comment by andyb3** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[gel_cover_report.py, line 39 at r1](https://reviewable.io/reviews/moka-guys/gel_reports/11#-LCDNknn5Ix2Kfzo9dGH:-LCT46FUBaZh8a1mI1Mi:b-896fix) ([raw file](https://github.com/moka-guys/gel_reports/blob/8ec6adbf47423147c7664660fa66c4cd2d19d2e0/gel_cover_report.py#L39)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

sorry, could you explain nargs='+' please
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/gel_reports/11)*

**Comment by aledj2** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/gel_reports/11)*

**Comment by aledj2** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/gel_reports/11#-:-LCTLwnL6f9lSgZSZ0lV:bnfp4nl)*

**Pull request merged**
